### ISSUE TITLE
Command not found & instructions

### ISSUE THREAD

**Issue by Hudsonzp** [surprisetalk/nowify#1]
You probably meant to release this for other engineers so apologies for being outside of your GTM early adopters 😅 I dabble, but I'm by no means good. Here's some issues others are likely to encounter:

- `nowify: command not found` even after adding it to my path. I also tried dragging it into usr/local/bin. This is probably user error, but unsure how to press forward.

- Didn't actually know a good chron to use. Settled on `brew install chron`. Might be something to suggest.

- I was a bit confused on the routines setup. Once I get it running I'm sure it'll be more clear.

Thanks for putting this together! Excited to try it @surprisetalk

**Comment by surprisetalk** [comment]
Thanks for being an early adopter! :)

1. Download the latest release [here](https://github.com/surprisetalk/nowify/releases).
2. In Terminal.app, run `chmod a+x ./Downloads/nowify` to make the script executable.
3. Run `./Downloads/nowify help`. A security window should pop up asking you what to do.
4. Head over to Security & Privacy in settings and click the "allow anyway" button.
5. Back in Terminal.app, run `while :; do ./Downloads/nowify annoy; sleep 2; done`.
6. In a separate Terminal.app window, run `./Downloads/nowify cli`.

If you drag it to `/usr/local/bin`, you should be able to write `nowify` instead of `./Downloads/nowify`.

Thanks for your patience! There are still _a lot_ of rough edges I need to iron out in this process.

**Comment by Hudsonzp** [comment]
We made it a step further, but seems like there's a bug in the compiled code when running nowify help, cli, etc.

```
./nowify help
error: Uncaught (in promise) Error: Unexpected quote in unquoted field (line 6, character 127)
                            this.onError(new Error(`Unexpected quote in unquoted field (${this.getCurrentPos()})`));
                                         ^
    at CSVReader.parseCycle (https://deno.land/x/csv@v0.8.0/reader.ts:313:42)
    at CSVReader.read (https://deno.land/x/csv@v0.8.0/reader.ts:123:18)
    at https://deno.land/x/csv@v0.8.0/reader.ts:507:29
    at new Promise (<anonymous>)
    at CSVRowReader.next (https://deno.land/x/csv@v0.8.0/reader.ts:504:23)
    at readCSVObjects (https://deno.land/x/csv@v0.8.0/reader.ts:684:22)
    at readCSVObjects.next (<anonymous>)
    at file:///Users/taylor/Developer/projects/nowify/nowify.ts:43:18
```

Chmod worked though! Totally understand the rough edges. This is the fun part of new products.

**Comment by surprisetalk** [comment]
Great news! Try putting this in `~/.config/nowify/routines.csv`:

```
days, start, end, duration, score, event, desc
MTWRFAU,  4, 10, 25, 3, exercise-1, Did you exercise? (1)
MTWRFAU, 10, 14, 25, 3, exercise-2, Did you exercise? (2)
MTWRFAU, 14, 18, 25, 3, exercise-3, Did you exercise? (3)
MTWRFAU,  0, 23, 25, 3,     work-1, Did you do 25 minutes of deep work? (1)
MTWRFAU,  0, 23, 25, 3,     work-2, Did you do 25 minutes of deep work? (2)
MTWRFAU,  0, 23, 25, 3,     work-3, Did you do 25 minutes of deep work? (3)
MTWRFAU,  0, 23, 25, 3,     work-4, Did you do 25 minutes of deep work? (4)
MTWRFAU,  0, 23, 25, 3,     work-5, Did you do 25 minutes of deep work? (5)
MTWRFAU,  0, 23, 25, 3,     work-6, Did you do 25 minutes of deep work? (6)
MTWRFAU,  0, 23, 25, 3,     work-7, Did you do 25 minutes of deep work? (7)
MTWRFAU,  0, 23, 25, 3,     work-8, Did you do 25 minutes of deep work? (8)
```

Easiest way to create the the file from the terminal is:
``` bash
mkdir -p ~/.config/nowify
touch ~/.config/nowify/routines.csv
open -a TextEdit ~/.config/nowify/routines.csv
```

**Comment by Hudsonzp** [comment]
It's alive! These sounds are such a better way to get my attention than popup/notifications for me. 

Will give you some feedback after I've used it for a week or so. Thanks for building this.
