### ISSUE TITLE
Routines.csv

### ISSUE THREAD

**Issue by wongjustin99** [surprisetalk/nowify#7]
What is the intention between the short example for the work routines? 

```
MTWRFAU,  0, 23, 25, 4,     work-1, Did you do 25 minutes of deep work? (1)
MTWRFAU,  0, 23, 25, 4,     work-2, Did you do 25 minutes of deep work? (2)
MTWRFAU,  0, 23, 25, 4,     work-3, Did you do 25 minutes of deep work? (3)
MTWRFAU,  0, 23, 25, 4,     work-4, Did you do 25 minutes of deep work? (4)
MTWRFAU,  0, 23, 25, 4,     work-5, Did you do 25 minutes of deep work? (5)
MTWRFAU,  0, 23, 25, 4,     work-6, Did you do 25 minutes of deep work? (6)
MTWRFAU,  0, 23, 25, 4,     work-7, Did you do 25 minutes of deep work? (7)
MTWRFAU,  0, 23, 25, 4,     work-8, Did you do 25 minutes of deep work? (8)
```

When I launch nowify, it just quickly prompts me for all 8 of these back-to-back. It doesn't seem like it's quite right. 

Maybe I am misinterpreting what the start and end periods are, but since these are all "work" I would have expected their schedules to be offset, instead of all of them covering the entire day. How is it supposed to work?

**Comment by surprisetalk** [comment]
Ah, I see how that can be confusing.

In the example, all 8 routines are active every day (`MTWRFAU`), during every hour of the day (0-23). To restrict the routine to typical working hours, you'd do weekdays (`MTWRF`) during working hours (9-17).

During those hours, nowify will choose the first uncompleted routine until you mark it "done" (or skip/snooze the routine).

So in this example, every ~25 minutes, nowify will start bugging you to mark the routine as "done" until you move onto the next one. And they will run in that order as long as they are in their active window.

Hope this helps!

**Comment by wongjustin99** [comment]
Ah! Okay I see, so I am supposed to be running into things and "waiting" them even if I have just completed one. Didn't realise that, I guess I am intended to "wait" them, or just quit out of the CLI at that point? 

I was initially expecting to finish each task, and then be reminded at a later point to do them. Sort of expecting brief periods of "inbox 0" before the next reminder kicked in. 

Will continue to refine my routine list and play with it. 

Thanks for the help!
